--KPI CALCULATION
--1. KPI 1: TOTAL PROFIT BY YEAR AND CITY

--JOINING CITY AND TAXI DATA ON THE BASIS OF CITY NAME AS TABLE 'KPI_TABLE_1'
SELECT A.CITY, A.POPULATION, A.USERS, B.TRANSACTION_ID, B.DATE_OF_TRAVEL, B.COMPANY, B.DISTANCE_TRAVELLED_KM, B.PRICE_CHARGED, B.COST_OF_TRIP
INTO KPI1_TABLE_1
FROM DBO.CITY A
INNER JOIN DBO.TAXI_DATA B ON A.CITY = B.CITY;

--KPI 1: TOTAL PROFIT BY YEAR AND CITY
SELECT CITY, DATEPART(YEAR, DATE_OF_TRAVEL) AS TRAVEL_YEAR, ROUND(SUM(PRICE_CHARGED - COST_OF_TRIP), 2) AS TOTAL_PROFITS 
INTO KPI1
FROM KPI1_TABLE_1
GROUP BY CITY, DATEPART(YEAR, DATE_OF_TRAVEL)
ORDER BY TRAVEL_YEAR;
-------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------

--2.KPI 2: USAGE OF TAXI BY GENDER AND COMPANY

--JOINING TAXI DATA AND TRANSACTIONS ON THE BASIS OF TRANSACTION_ID
SELECT A.TRANSACTION_ID, A.CUSTOMER_ID, A.PAYMENT_MODE, B.DATE_OF_TRAVEL, B.COMPANY, B.DISTANCE_TRAVELLED_KM, B.PRICE_CHARGED, B.COST_OF_TRIP
INTO KPI2_TABLE_1
FROM DBO.TRANSACTIONS A
INNER JOIN DBO.Taxi_Data B ON A.TRANSACTION_ID = B.TRANSACTION_ID;

--NOW JOINING THE KPI2_TABLE_1 WITH CUSTOMERS TABLE ON THE BASIS OF CUSTOMER_ID
SELECT KPI2_TABLE_1.*, C.GENDER, C.AGE, C.INCOME_USD_MONTH
INTO KPI2_TABLE_2
FROM KPI2_TABLE_1
INNER JOIN CUSTOMERS C ON KPI2_TABLE_1.CUSTOMER_ID = C.CUSTOMER_ID;

--KPI 2: USAGE OF TAXI BY GENDER AND COMPANY
SELECT COMPANY,GENDER,COUNT(TRANSACTION_ID) AS Usage,
FORMAT((COUNT(TRANSACTION_ID) * 100.0 / (SELECT COUNT(TRANSACTION_ID) FROM KPI2_TABLE_2)), 'N2') AS 'Users as per Company and Gender'
INTO KPI2
FROM KPI2_TABLE_2
GROUP BY COMPANY, GENDER;